### ISSUE TITLE
Add delegate data

### ISSUE THREAD

**Issue by hamidra** [jeluard/governance-ui#165]
We need to pull and aggregate some information regarding delegates to present them to the users. 
The below schema is based what is going to be presented in the delegate Cards.
```
{
    account: {
      name:'can be pulled from identity pallet if available',
      address:'account address'
    },
    roles: ['nominator', 'fellow', 'validator', ...],
    bio: <since currently there is no profile we can have some logic to autogenerate a paragraph based on the delegates information to be used as their bio> >
    stats: [
      { title: 'Most active track', value: 'Staking admin' },
      { title: 'Participation', value: '75.71%' },
      { title: 'Representing', value: '135 addresses' },
      { title: 'DOT', value: '24k DOT' },
    ],
  }
  ```
  I believe these are reasonable to present to the users in the first iteration.

**Comment by jeluard** [comment]
Some ideas:

* fellows list should already be in the state
* we could add validators and identity pallet
* delegates details is there

Then it should be possible to extract stats, bio and roles by matching those different subsets of data dynamically via some function. Hopefully it's not needed to add those derived info to the state.
